version: "3"

services: 
  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
    env_file:
      - .env
  python:
    build: .
    tty: true
    volumes: 
      - .:/var/wordle
    env_file:
      - .env
    links:
      - db
volumes:
  db:
    driver: local
